org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.java.installations.auto-download=false
android.useAndroidX=true
android.builder.sdkDownload=false
kotlin.code.style=official
kotlin.mpp.applyDefaultHierarchyTemplate=false
APP_VERSION_NAME=0.1.0
APP_VERSION_CODE=6
